# Generated by Django 5.1.1 on 2024-09-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_object_address_alter_object_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_meter_type', models.CharField(max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='flow_meter_photos')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=50)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flow_meter_serial_number', models.CharField(max_length=50)),
                ('flow_meter_year', models.CharField(max_length=4)),
                ('owner', models.CharField(max_length=50)),
                ('contractor', models.CharField(choices=[('Hududgazta`minot', 'Hududgazta`minot'), ('UzGazTrade', 'UzGazTrade'), ('O`zneftgaz', 'O`zneftgaz'), ('SanEG', 'SanEG'), ('Boshqa', 'Boshqa')], max_length=50)),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('flow_meter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.flowmetertype')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FlowMeterSertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('url_sertificate', models.FileField(blank=True, null=True, upload_to='sertificates')),
                ('is_active', models.CharField(choices=[('Amalda', 'Amalda'), ('Amalda emas', 'Amalda emas')], default='Amalda', max_length=20)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.meter')),
            ],
        ),
    ]
