# Generated by Django 5.1.1 on 2024-10-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_flowmetertype_meter_flowmetersertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowmetersertificate',
            name='object',
        ),
    ]
