# Generated by Django 5.1.1 on 2024-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_remove_flowmetersertificate_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
