# Generated by Django 5.1.1 on 2024-10-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_object_latitude_alter_object_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='power',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='object',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='objects.organization'),
        ),
    ]
