# Generated by Django 5.1.1 on 2024-10-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0003_flowmetertype_meter_flowmetersertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrificePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('d20', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outer_diameter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('e', models.FloatField()),
                ('d20_calculated', models.FloatField(max_length=2)),
                ('p_max', models.FloatField()),
                ('pressure', models.FloatField()),
                ('p_unit', models.CharField(choices=[('kPa', 'kPa'), ('MPa', 'MPa'), ('kgf/m2', 'kgf/m2'), ('kgf/sm2', 'kgf/sm2'), ('bar', 'bar')], default='kPa', max_length=10)),
                ('temperature', models.FloatField()),
                ('dp_max', models.FloatField()),
                ('dp_min', models.FloatField()),
                ('dp_unit', models.CharField(choices=[('kPa', 'kPa'), ('MPa', 'MPa'), ('kgf/m2', 'kgf/m2'), ('kgf/sm2', 'kgf/sm2'), ('bar', 'bar')], default='kPa', max_length=10)),
                ('q_max', models.FloatField()),
                ('q_min', models.FloatField()),
                ('betta', models.DecimalField(decimal_places=2, max_digits=3)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('installed', models.CharField(choices=[('O`rnatilgan', 'O`rnatilgan'), ('O`rnatilmagan', 'O`rnatilmagan')], default='O`rnatilmagan', max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('meter', models.ForeignKey(blank=True, limit_choices_to={'object_id': models.F('object_id')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.meter')),
            ],
        ),
    ]
