# Generated by Django 5.1.1 on 2024-10-10 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_alter_object_latitude_alter_object_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('flowmeter_volume', models.FloatField()),
                ('ns_0', models.FloatField()),
                ('ns_1', models.FloatField()),
                ('ns_2', models.FloatField()),
                ('ns_3', models.FloatField()),
                ('ns_4', models.FloatField()),
                ('ns_5', models.FloatField()),
                ('ns_6', models.FloatField()),
                ('ns_7', models.FloatField()),
                ('restored_volume', models.FloatField(editable=False)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.meter')),
            ],
        ),
    ]
