# Generated by Django 5.1.1 on 2024-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restored_volume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='ns_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_7',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
