# Generated by Django 5.1.1 on 2024-10-29 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_object_latitude_alter_object_longitude'),
        ('restored_volume', '0002_alter_volume_ns_0_alter_volume_ns_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='objects.meter'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_0',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volume',
            name='ns_7',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='objects.organization')),
            ],
        ),
        migrations.AddField(
            model_name='volume',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='restored_volume.period'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('meter', 'period')},
        ),
    ]
